### ISSUE TITLE
[MOSL] NPE for non-existent patterns instead of helpful error message

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-issue-tracking-system#451]
Using control flow with non-existent patterns leads to this:

java.lang.NullPointerException
	at org.moflon.mosl.utils.PathResolver.getPattern(PathResolver.java:296)
	at org.moflon.mosl.utils.PathResolver.copyPatterns(PathResolver.java:237)
	at org.moflon.mosl.utils.PathResolver.resolveAllPathes(PathResolver.java:253)
	at MOSLCodeAdapter.moslPlus.impl.MOSLConverterAdapterImpl.resolve(MOSLConverterAdapterImpl.java:254)

**Comment by anthonyanjorin** [comment]
We also had a nice QuickFix for creating patterns.  It is almost impossible to work with the editor without this functionality.
