### ISSUE TITLE
[MOSL] NPE when opposites are wrong

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-issue-tracking-system#516]
When using invalid references in *_constraints.mconf*, I get a NPE:

java.lang.NullPointerException
	at org.moflon.ide.core.runtime.builders.MOSLBuilder.processMOSL(MOSLBuilder.java:134)
	at org.moflon.ide.core.runtime.builders.MOSLBuilder.visit(MOSLBuilder.java:56)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:69)

Full stacktrace: http://pastebin.com/5m9UgwkD

**Comment by RolandKluge** [comment]
@anthonyanjorin FYI

**Comment by SchroedingersCatIsUndead** [comment]
NPE should not exist anymore
