### ISSUE TITLE
[MOSL] NPE when creating object variables

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-issue-tracking-system#518]
If I create an object variable with a wrong type, an NPE is thrown.

E.g. in the tutorial, I had the following typo:

pattern moveFigure {
	@floor : Florr 
}

This is the top of the stacktrace:
java.lang.NullPointerException
	at org.moflon.ide.core.runtime.builders.MOSLBuilder.processMOSL(MOSLBuilder.java:134)
	at org.moflon.ide.core.runtime.builders.MOSLBuilder.visit(MOSLBuilder.java:56)

**Comment by SchroedingersCatIsUndead** [comment]
NPE should not exist anymore and a Marker appears
