### ISSUE TITLE
NoSuchElementException on showing local completeness error

### ISSUE THREAD

**Issue by mabilov** [eMoflon/emoflon-issue-tracking-system#528]
When there is LocalCompletenessException during synchronization, when trying to retrieve message from the exception another exception occurs:
Exception in thread "main" java.util.NoSuchElementException
	at java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.util.HashMap$KeyIterator.next(Unknown Source)
	at org.moflon.tgg.algorithm.exceptions.LocalCompletenessException.getMessage(LocalCompletenessException.java:26)
	at org.moflon.tgg.algorithm.synchronization.SynchronizationHelper.performSynchronization(SynchronizationHelper.java:430)

The code on this line is 
25  while(itrNames.hasNext()){
26      Map<String, EObject> mapping = itrMappings.next();

As you can see that the iterator itrMappings isn't checked before it is used. Possible improvements would be for example:
25  while(itrNames.hasNext() && itrMappings.next()){
26      Map<String, EObject> mapping = itrMappings.next();

**Comment by erhanleblebici** [comment]
done. thanks for the robustness suggestion :)
