### ISSUE TITLE
[Democles] Error during code generation

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-issue-tracking-system#550]
with our current beta (after the latest hacker day session), I keep getting this error when generating code:

````
14:54:45 ERROR [democles.DefaultTemplateConfiguration::19] - [ST runtime error] context [/ControlFlowGenerator/ScopeImpl /ControlFlowGenerator/Node /ControlFlowGenerator/ForEachImplRegularPatternInvocationImpl /ControlFlowGenerator/NextActions /ControlFlowGenerator/NextActions /ControlFlowGenerator/PerformAction /ControlFlowGenerator/NodeDeletionImplInForEachImpl /ControlFlowGenerator/DefaultPerformAction] 2:1 no such property or can't access: ControlFlow.impl.NodeDeletionImpl.freeParameters
Caused by: org.stringtemplate.v4.misc.STNoSuchPropertyException: no such property: ControlFlow.impl.NodeDeletionImpl.freeParameters
	at org.stringtemplate.v4.misc.ObjectModelAdaptor.throwNoSuchProperty(ObjectModelAdaptor.java:167)
	at org.stringtemplate.v4.misc.ObjectModelAdaptor.getProperty(ObjectModelAdaptor.java:89)
	at org.stringtemplate.v4.Interpreter.getObjectProperty(Interpreter.java:1200)
	at org.stringtemplate.v4.Interpreter._exec(Interpreter.java:210)
````

To reproduce take for instance our demo example (or actually I think any example).

**Comment by gervarro** [comment]
(Hopefully ;-)) fixed by commit 319
